import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "highlight.js/styles/github-dark.css";
import Link from "next/link";
import { AnimatedGradientText } from "@/components/ui/AnimatedGradientText";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased, max-w-[900px] mx-auto bg-slate-950 text-white`}
      >
        <div className="container mx-auto py-10">
          <Link href={"/"}>
            <AnimatedGradientText
              className={
                "bg-gradient-to-br from-green-500 via-blue-300 to-rose-700 font-extrabold py-2"
              }
            >
              Machine coding Components
            </AnimatedGradientText>
          </Link>
          {children}
        </div>
      </body>
    </html>
  );
}
