name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Use the latest Node.js version
      - name: Setup Node.js (latest)
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build the Next.js app
      - name: Build Next.js app
        run: npm run build

      # 5️⃣ Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --confirm
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
